Site/Controllers/DadosController.cs
using Infra.Context;
using Infra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;

namespace Site.Controllers
{
    [Authorize]
    [Route("/admin/Estatisticas/{action=Index}")]
    public class DadosController : Controller
    {
        public Context _context;
        private IWebHostEnvironment _hostEnvironment;

        public DadosController(Context context, IWebHostEnvironment environment)
        {
            _context = context;
            _hostEnvironment = environment;
        }

        public IActionResult Index()
        {
            return View(_context.Dado.AsNoTracking().OrderBy(x => x.Ordenacao).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.Edit = false;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisableRequestSizeLimit]
        public IActionResult Create(Dado Dado, IFormFile? imagem)
        {
            ViewBag.Edit = false;

            Dado.Ordenacao = _context.Dado.AsNoTracking().Count();

            if (imagem != null)
            {
                var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

                path = Path.Combine(path, "imagens");

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                var filename = Dado.DadoId.ToString() + "." + imagem.ContentType.Split("/")[1].ToString();

                path = Path.Combine(path, filename);

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    imagem.CopyTo(stream);
                }

                Dado.Caminho = filename;
            }

            _context.Dado.Add(Dado);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(Guid id)
        {
            ViewBag.Edit = true;

            return View(nameof(Create), _context.Dado.First(x => x.DadoId == id));
        }

        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Dado Dado, IFormFile? imagem, bool imagemalterada)
        {
            if (imagemalterada)
            {
                if (imagem != null)
                {
                    var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

                    path = Path.Combine(path, "imagens");

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    var filename = Dado.DadoId.ToString() + "." + imagem.ContentType.Split("/")[1].ToString();

                    path = Path.Combine(path, filename);

                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        imagem.CopyTo(stream);
                    }

                    Dado.Caminho = filename;
                }
            }

            _context.Dado.Update(Dado);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public JsonResult remover(Guid id)
        {
            var Dado = _context.Dado.First(x => x.DadoId == id);

            _context.Dado.Remove(Dado);

            _context.SaveChanges();

            if (!string.IsNullOrEmpty(Dado.Caminho))
            {
                var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

                path = Path.Combine(path, "imagens");

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                path = Path.Combine(path, Dado.Caminho);

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }

            return new JsonResult(new { });
        }

        public IActionResult SalvarOrdenacao(List<Dado> Dados)
        {
            foreach (var p in Dados)
            {
                var Dado = _context.Dado.AsNoTracking().First(x => x.DadoId == p.DadoId);

                Dado.Ordenacao = Dados.IndexOf(p);

                _context.Dado.Update(Dado);
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Site/Controllers/ImagensProjetoController.cs
using Infra.Context;
using Infra.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;

namespace Site.Controllers
{
    public class ImagensProjetoController : Controller
    {
        private Context _context;
        private IWebHostEnvironment _hostEnvironment;

        public ImagensProjetoController(Context context, IWebHostEnvironment environment)
        {
            _context = context;
            _hostEnvironment = environment;
        }

        public ActionResult Index(Guid projetoid)
        {
            ViewBag.projetoid = projetoid;

            return View(_context.ImagemProjeto.AsNoTracking().Where(x => x.ProjetoId == projetoid).OrderBy(x => x.Ordenacao).ToList());
        }

        // GET: ImagensProjetoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ImagensProjetoController/Create
        public ActionResult Create(Guid projetoid)
        {
            ViewBag.Edit = false;

            return View(new ImagemProjeto() { ProjetoId = projetoid });
        }

        // POST: ImagensProjetoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ImagemProjeto imagemProjeto, IFormFile? imagem)
        {
            ViewBag.Edit = false;

            imagemProjeto.Ordenacao = _context.ImagemProjeto.AsNoTracking().Count();           

            if (imagem != null)
            {
                var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

                path = Path.Combine(path, "imagens");

                path = Path.Combine(path, "carrossel-" + imagemProjeto.ProjetoId.ToString());

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                var filename = imagemProjeto.ImagemProjetoId.ToString() + "." + imagem.ContentType.Split("/")[1].ToString();

                path = Path.Combine(path, filename);

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    imagem.CopyTo(stream);
                }

                imagemProjeto.Caminho = filename;
            }

            _context.ImagemProjeto.Add(imagemProjeto);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index), new { projetoid = imagemProjeto.ProjetoId });
        }

        // GET: ImagensProjetoController/Edit/5
        public ActionResult Edit(Guid id)
        {
            ViewBag.Edit = true;

            return View(nameof(Create), _context.ImagemProjeto.First(x => x.ImagemProjetoId == id));
        }

        // POST: ImagensProjetoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ImagemProjeto imagemProjeto, IFormFile? imagem, bool imagemalterada)
        {
            ViewBag.Edit = true;

            var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

            path = Path.Combine(path, "imagens");

            path = Path.Combine(path, "carrossel-" + imagemProjeto.ProjetoId.ToString());

            if (imagemalterada)
            {
                if (imagem != null)
                {
                    path = Path.Combine(path, "imagens");

                    path = Path.Combine(path, "carrossel-" + imagemProjeto.ProjetoId.ToString());

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    var filename = imagemProjeto.ImagemProjetoId.ToString() + "." + imagem.ContentType.Split("/")[1].ToString();

                    path = Path.Combine(path, filename);

                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        imagem.CopyTo(stream);
                    }

                    imagemProjeto.Caminho = filename;
                }
            }

            _context.ImagemProjeto.Update(imagemProjeto);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index), new { projetoid = imagemProjeto.ProjetoId });
        }

        public IActionResult SalvarOrdenacao(List<ImagemProjeto> imagens, Guid projetoid)
        {
            foreach (var p in imagens)
            {
                var imagem = _context.ImagemProjeto.AsNoTracking().First(x => x.ImagemProjetoId == p.ImagemProjetoId);

                imagem.Ordenacao = imagens.IndexOf(p);

                _context.ImagemProjeto.Update(imagem);
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index), new { projetoid = projetoid });
        }

        public async Task<FileResult> ObterImagem(string filename, Guid projetoid)
        {
            var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

            path = Path.Combine(path, "imagens");

            path = Path.Combine(path, "carrossel-" + projetoid.ToString(), filename);

            var provider = new FileExtensionContentTypeProvider();
            string contentType;
            if (!provider.TryGetContentType(filename, out contentType))
            {
                contentType = "application/octet-stream";
            }

            var bytes = await System.IO.File.ReadAllBytesAsync(path);

            return File(bytes, contentType);
        }

        public JsonResult remover(Guid id)
        {
            var imagem = _context.ImagemProjeto.First(x => x.ImagemProjetoId == id);

            _context.ImagemProjeto.Remove(imagem);

            _context.SaveChanges();

            if (!string.IsNullOrEmpty(imagem.Caminho))
            {
                var path = Directory.GetParent(_hostEnvironment.ContentRootPath).Parent.FullName;

                path = Path.Combine(path, "imagens");

                path = Path.Combine(path, "carrossel-" + imagem.ProjetoId.ToString(), imagem.Caminho);

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }

            return new JsonResult(new { });
        }
    }
}

Site/Controllers/MenuController.cs
using Infra.Context;
using Infra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Site.Controllers
{
    [Authorize]
    [Route("/admin/menus/{action=Index}")]
    public class MenuController : Controller
    {
        public Context _context;
        private IWebHostEnvironment _hostEnvironment;

        public MenuController(Context context, IWebHostEnvironment environment)
        {
            _context = context;
            _hostEnvironment = environment;
        }

        public IActionResult Index()
        {
            return View(_context.Menu.AsNoTracking().OrderBy(x => x.Ordenacao).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.Edit = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Menu menu)
        {
            ViewBag.Edit = false;
            _context.Menu.Add(menu);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(Guid id)
        {
            ViewBag.Edit = true;

            return View(nameof(Create), _context.Menu.First(x => x.MenuId == id));
        }


        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Menu menu, IFormFile? imagem, bool imagemalterada)
        {
            _context.Menu.Update(menu);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public JsonResult remover(Guid id)
        {
            var menu = _context.Menu.First(x => x.MenuId == id);

            _context.Menu.Remove(menu);

            _context.SaveChanges();

            return new JsonResult(new { });
        }

        public IActionResult SalvarOrdenacao(List<Menu> menus)
        {
            foreach (var p in menus)
            {
                var Menu = _context.Menu.AsNoTracking().First(x => x.MenuId == p.MenuId);

                Menu.Ordenacao = menus.IndexOf(p);

                _context.Menu.Update(Menu);
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Site/Controllers/PerguntasController.cs
using Infra.Context;
using Infra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;

namespace Site.Controllers
{
    [Authorize]
    [Route("/admin/Perguntas/{action=Index}")]
    public class PerguntasController : Controller
    {
        public Context _context;
        private IWebHostEnvironment _hostEnvironment;

        public PerguntasController(Context context, IWebHostEnvironment environment)
        {
            _context = context;
            _hostEnvironment = environment;
        }

        public IActionResult Index()
        {
            return View(_context.Pergunta.AsNoTracking().OrderBy(x => x.Ordenacao).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.Edit = false;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisableRequestSizeLimit]
        public IActionResult Create(Pergunta Pergunta, IFormFile? imagem)
        {
            ViewBag.Edit = false;

            if (Pergunta.Link == null)
                Pergunta.Link = "";

            if (Pergunta.NomeLink == null)
                Pergunta.NomeLink = "";

            _context.Pergunta.Add(Pergunta);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(Guid id)
        {
            ViewBag.Edit = true;

            return View(nameof(Create), _context.Pergunta.First(x => x.PerguntaId == id));
        }

        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(Pergunta Pergunta, IFormFile? imagem, bool imagemalterada)
        {
            if (Pergunta.Link == null)
                Pergunta.Link = "";

            if (Pergunta.NomeLink == null)
                Pergunta.NomeLink = "";

            _context.Pergunta.Update(Pergunta);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public JsonResult remover(Guid id)
        {
            var Pergunta = _context.Pergunta.First(x => x.PerguntaId == id);

            _context.Pergunta.Remove(Pergunta);

            _context.SaveChanges();


            return new JsonResult(new { });
        }


        public IActionResult SalvarOrdenacao(List<Pergunta> Perguntas)
        {
            foreach (var p in Perguntas)
            {
                var pergnta = _context.Pergunta.AsNoTracking().First(x => x.PerguntaId == p.PerguntaId);

                pergnta.Ordenacao = Perguntas.IndexOf(p);

                _context.Pergunta.Update(pergnta);
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Site/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Site.Controllers
{
    [Authorize]
    [Route("/admin/usuarios/{action=Index}")]
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()

        {
            return View();
        }
    }
}

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Custom CSS -->
    <link href="~/dist/css/style.css" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
</head>

<body class="skin-default-dark fixed-layout">

    <div id="main-wrapper">


        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="navbar-brand">
                        <b>
                            <img src="~/assets/img/logom2.png" style="max-height:50px;width:100%" alt="homepage" class="dark-logo" />
                        </b>
                    </a>
                </div>


                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item hidden-sm-up">
                            <a class="nav-link nav-toggler waves-effect waves-light"
                               href="javascript:void(0)"><i class="ti-menu"></i></a>
                        </li>
                    </ul>
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href=""
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Olá @User.Identity?.Name
                            </a>

                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="@Url.Action("Logout","Login")"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                sair
                            </a>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>


        <aside class="left-sidebar">
            <div class="d-flex no-block nav-text-box align-items-center">
                <a class="waves-effect waves-dark ml-auto hidden-sm-down" href="javascript:void(0)">
                    <i class="ti-menu"></i>
                </a>
                <a class="nav-toggler waves-effect waves-dark ml-auto hidden-sm-up" href="javascript:void(0)">
                    <i class="ti-menu ti-close"></i>
                </a>
            </div>
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Menu")" aria-expanded="false">
                                <i class="fa fa-window-minimize" aria-hidden="true"></i><span class="hide-menu">Menu</span>
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Carrousel")" aria-expanded="false">
                                <i class="fa fa-files-o" aria-hidden="true"></i></i><span class="hide-menu">Carrossel</span>
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Sobre")" aria-expanded="false">
                                <i class="fa fa-list-alt" aria-hidden="true"></i><span class="hide-menu"></span>Sobre nós
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","MiniCarrousel")" aria-expanded="false">
                                <i class="fa fa-clipboard" aria-hidden="true"></i><span class="hide-menu"></span>Mini Carrossel
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Dados")" aria-expanded="false">
                                <i class="fa fa-info-circle" aria-hidden="true"></i><span class="hide-menu"></span>Estatísticas
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Projetos")" aria-expanded="false">
                                <i class="fa fa-handshake-o" aria-hidden="true"></i></i><span class="hide-menu"></span>Projetos
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Perguntas")" aria-expanded="false">
                                <i class="fa fa-question-circle" aria-hidden="true"></i><span class="hide-menu"></span>Perguntas
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="@Url.Action("Index","Usuario")" aria-expanded="false">
                                <i class="fa fa-user" aria-hidden="true"></i><span class="hide-menu"></span>Usuários
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>


        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="row page-titles">
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="~/assets/vendor/jquery.min.js"></script>
    <script src="~/dist/js/custom.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function ()
        {
            $('.table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_pt.json"
                },
                sortable : false,
                order: []
            });
        });

         $( ".table" ).sortable
         ({
            items: "tr",
            cursor: 'move',
            opacity: 0.6
         });
    </script>

    @RenderSection("Scripts", required: false)

</body>

</html>

Site/Views/Shared/_imagensprojeto.cshtml
@model IEnumerable<Infra.Entities.ImagemProjeto>
@*<style>

    .carousel-item.principal {
    padding-left: 25%;
    }

    body {
    background-color: black;
    }

    @@media screen and (max-width: 475px) {

    .carousel-item.principal {
    padding-left: 33%;
    }

    button.btn.btn-primary {
    margin-bottom: 3%;
    }

    }
    </style>*@
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="modalimgs" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="carouselExampleeControls" style="width:100%" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    @foreach (var imagem in Model.OrderBy(x => x.Ordenacao))
                    {
                        if (imagem.ImagemProjetoId == Model.First().ImagemProjetoId)
                        {
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="@Url.Action("ObterImagem","ImagensProjeto",new {filename = imagem.Caminho, projetoid = imagem.ProjetoId})">
                            </div>
                        }
                        else
                        {
                            <div class="carousel-item">
                                <img class="d-block w-100" src="@Url.Action("ObterImagem","ImagensProjeto",new {filename = imagem.Caminho, projetoid = imagem.ProjetoId})">
                            </div>
                        }
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleeControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleeControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    </div>
</div>